sources:
  - name: Stripe
    handler:
      openapi:
        source: https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.yaml
        baseUrl: https://api.stripe.com
        operationHeaders:
          Authorization: "Bearer ${STRIPE_TOKEN}"
    transforms:
      - prefix:
          value: STRIPE_
          includeRootOperations: true
  - name: Github
    handler:
      graphql:
        endpoint: https://api.github.com/graphql
        headers:
          Authorization: bearer ${GH_ACCESS_TOKEN}
    transforms:
      - prefix:
          value: GITHUB_
          includeRootOperations: true
